### ISSUE TITLE
Error in 'collapsetime'

### ISSUE THREAD

**Issue by arielephrat** [jamesmf/mnistCRNN#2]
Thanks so much for publishing this code!

When trying to run your code, I get the following error:
**TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'**

This is because in the following line within 'collapsetime'
`newshape = [np.prod(x.get_shape()[0:2].as_list()),] + x.get_shape()[2:].as_list()`
the result of
`x.get_shape()[0:2].as_list()`
is
`[None,8]`
which produces the above error when trying to compute the product of both list elements.

Am I missing something here?

Thanks!

**Comment by jamesmf** [comment]
1) Have you added the file `theano_backend.py` to `/keras/backend/` in your site-packages, as in the keras-extra documentation?

2) What versions of Keras and Theano are you using?This is currently only tested for `Keras==0.3.1` and `Theano==0.8.0`

**Comment by arielephrat** [comment]
Sorry about that. I didn't realize it was only tested using Theano backend.
In any case, it works now. Thanks!
