### ISSUE TITLE
Mismatch in the shape of training and testing data

### ISSUE THREAD

**Issue by Sroy20** [jamesmf/mnistCRNN#8]
Hi again,

In the script addMNISTrnn.py, the way the training and testing matrices are initialized are:

X_train     = np.zeros((examplesPer,maxToAdd,size,size,1))
X_test     = np.zeros((examplesPer,maxToAdd,1,size,size))

So, the position of the depth channel is different for both of them. This throws an error when during testing. 

In my case, I changed the shape of X_test and the bit of code (for loop) following that and it works seamlessly.

**Comment by jamesmf** [comment]
Thanks for pointing out. I uncommented the 'test' section and fixed the dim ordering there as well.
